language: node_js
notifications:
  email: false
node_js:
  - '4'
before_install:
  - npm cache clean -f
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
  - npm install
  - npm i -g typings
  - typings install
script:
  - npm run build
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/