language: node_js
node_js:
  - "0.10"
  - "4.2"
sudo: false
before_script:
  - npm install
  - npm i -g typings
  - typings install
script: npm run build
deploy:
  provider: npm
  email: arthur.xavierx@gmail.com
  api_key: $NPM_AUTH_TOKEN
